
# ________________________________________________________ #
#  These are in relation to the robot base frame in meters #
# ________________________________________________________ #


# Sensor safe starting position x_max limit #
sensor_x_max : 0.05
# Sensor safe starting position x_min limit #
sensor_x_min : -0.05                    
# Sensor safe starting position y_max limit #
sensor_y_max : 0.6    
# Sensor safe starting position y_min limit #
sensor_y_min : 0.5     
# Sensor safe starting position z_max limit #
sensor_z_max : 0.7    
 # Sensor safe starting position z_min limit #
sensor_z_min : 0.6                     

# ________________________________________________________  #
#  These are in relation to the robot base frame in radians #
# ________________________________________________________  #


# Sensor safe starting orientation az_max limit #
sensor_az_max : 1.57  
# Sensor safe starting orientation az_min limit #
sensor_az_min : -1.57     
# Sensor safe starting orientation el_max limit #
sensor_el_max : 1.57  
# Sensor safe starting orientation el_min limit #
sensor_el_min : -1.57
# Sensor safe starting orientation ro_max limit #
sensor_ro_max : 1.57  
# Sensor safe starting orientation ro_min limit #
sensor_ro_min : -1.57           
